### PR TITLE
Fix Awake Hook

### LINKED ISSUE #187: Awake hook does not work
We recently moved our deserialization logic to Awake and it is interfering with user code.

### PR DESCRIPTION
**Pull request by spacepluk**
ArcadiaBehavior is the base class for all the hooks and has some logic implemented in the Awake method.  For the Awake hook to work it needs to call the base class' Awake method.

This patch updates the code used to generate the hooks so that you can specify when to call the super class and what type of method override to use.  It also changes the generated AwakeHook class.

Fixes #187

### CODE REVIEW

File: Source/arcadia/internal/components.clj [hunk 1]
```diff
@@ -17,6 +17,14 @@
...
        (map (comp str char))))
 
+(def overrides
+  "Which methods of ArcadiaBehaviour should be overriden/hidden."
+  '{Awake override})
+
+(def call-base
+  "Which overriden methods should call the base method."
+  '{Awake true})
+
```
Comment (nasser) [inline Source/arcadia/internal/components.clj]: Is there ever a situation when you would *not* call the base method in an overridden method? My feeling is that we could just use the `overrides` map and not have to keep two maps in sync.

Realistically though this is the only method that will need this, so its not a terribly big deal.
